# Generated by Django 4.1.5 on 2023-05-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookModel',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='bookApp.author'),
        ),
        migrations.DeleteModel(
            name='ReplyCommentsModel',
        ),
    ]
