# Generated by Django 4.1.5 on 2023-05-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0003_delete_facebookmodel_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='bookApp.author'),
            preserve_default=False,
        ),
    ]
