# Generated by Django 4.1.5 on 2023-05-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0005_facebookmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='massage',
            new_name='comment',
        ),
    ]
